"""Rules command - Universal Rule Generation."""

import click
from pathlib import Path
from rich.console import Console
from typing import List

from ask.utils.filesystem import get_safe_cwd

console = Console()


def discover_rules(use_global: bool = False) -> List[Path]:
    """Discover rule markdown files in the universal rules directory."""
    if use_global:
        rules_dir = Path.home() / ".agents" / "rules"
    else:
        rules_dir = get_safe_cwd() / ".agents" / "rules"

    if not rules_dir.exists() or not rules_dir.is_dir():
        return []

    rules = []
    for item in rules_dir.iterdir():
        if item.is_file() and item.suffix.lower() in [".md", ".txt"]:
            rules.append(item)
            
    return sorted(rules)


def compile_rules_content(rules: List[Path]) -> str:
    """Concatenate rules into a single comprehensive string."""
    contents = []
    contents.append("<!-- Auto-generated by ask rules compile. Do not edit manually. -->")
    contents.append("# Universal Agent Rules\n")
    
    for idx, rule_file in enumerate(rules, 1):
        rule_name = rule_file.stem.replace('-', ' ').replace('_', ' ').title()
        contents.append(f"## {idx}. {rule_name}")
        contents.append(rule_file.read_text(encoding="utf-8").strip())
        contents.append("\n---\n")
        
    return "\n".join(contents)


@click.group()
def rules():
    """Universal Rule Generation for AI Agents."""
    pass


@rules.command()
@click.option("--global", "-g", "use_global", is_flag=True, help="Compile global rules (~/.agents/rules)")
def compile(use_global: bool):
    """Compile .agents/rules/ into .cursorrules, CLAUDE.md, and .agent/rules/rules.md"""
    rule_files = discover_rules(use_global)
    
    if not rule_files:
        scope = "global (~/.agents/rules/)" if use_global else "local (.agents/rules/)"
        console.print(f"[dim]No .md or .txt rules found in {scope}.[/dim]")
        console.print("[dim]Create a rule file (e.g., .agents/rules/typescript.md) and run again.[/dim]")
        return

    console.print(f"[dim]Found {len(rule_files)} rule(s). Compiling...[/dim]")
    
    compiled_content = compile_rules_content(rule_files)
    
    # Target files
    if use_global:
        targets = [
            Path.home() / ".cursorrules",
            Path.home() / ".claude.md", # Claude Code global is typically ~/.claude.md or similar
            Path.home() / ".agent" / "rules" / "rules.md"
        ]
    else:
        root = get_safe_cwd()
        targets = [
            root / ".cursorrules",
            root / "CLAUDE.md",
            root / ".agent" / "rules" / "rules.md"
        ]
        
    success_count = 0
    for target in targets:
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(compiled_content, encoding="utf-8")
            console.print(f"  [green]✓[/green] Wrote to {target}")
            success_count += 1
        except Exception as e:
            console.print(f"  [red]✗[/red] Failed to write {target}: {e}")
            
    console.print(f"\n[green]✓[/green] Compiled to {success_count} format(s)")
