#!/usr/bin/env python3
import os
import shutil
from pathlib import Path

# Paths relative to project root (ASK)
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SKILL_CATS = ["coding", "planning", "tooling"]

def migrate_skill(skill_path: Path):
    """
    Migrates a single skill to the Gold Standard structure.
    """
    skill_name = skill_path.name
    print(f"Migrating {skill_name}...")
    
    # 1. Ensure Directories exist
    scripts_dir = skill_path / "scripts"
    assets_dir = skill_path / "assets"
    tests_dir = skill_path / "tests"
    
    scripts_dir.mkdir(exist_ok=True)
    assets_dir.mkdir(exist_ok=True)
    tests_dir.mkdir(exist_ok=True)
    
    # 2. Create Placeholder Validation Script
    validate_script = scripts_dir / "validate.py"
    if not validate_script.exists():
        with open(validate_script, "w") as f:
            f.write(f"""#!/usr/bin/env python3
# Placeholder validation logic for {skill_name}
# Automatically generated by migration script
import sys

print("Validation passed (placeholder).")
sys.exit(0)
""")
        # Make executable
        os.chmod(validate_script, 0o755)
        print(f"  - Created scripts/validate.py")
        
    # 3. Create Placeholder Test Case
    test_case = tests_dir / "case1_placeholder.md"
    if not test_case.exists() and not any(tests_dir.glob("*.md")):
        with open(test_case, "w") as f:
            f.write(f"""# Test Case: Placeholder for {skill_name}

## Input
"Run the skill to verify functionality."

## Expected Output
Success
""")
        print(f"  - Created tests/case1_placeholder.md")
        
    # 4. Handle README.md (RESTORE if moved, do NOT move)
    legacy_readme = assets_dir / "readme_legacy.md"
    readme = skill_path / "README.md"
    
    # If we previously moved it, move it back!
    if legacy_readme.exists() and not readme.exists():
        shutil.move(str(legacy_readme), str(readme))
        print(f"  - Restored assets/readme_legacy.md -> README.md (GitHub compatibility)")
            
    print(f"  - Structure updated.")

def main():
    skills_root = PROJECT_ROOT / "skills"
    
    for category in SKILL_CATS:
        cat_path = skills_root / category
        if not cat_path.exists():
            continue
            
        # Robust iteration: skip .DS_Store and other files
        for item in cat_path.iterdir():
            # Check name FIRST to avoid stat() on restricted files
            if item.name.startswith("."):
                continue
                
            try:
                if item.is_dir():
                    migrate_skill(item)
            except OSError:
                # Ignore permission errors or other stat failures
                continue

if __name__ == "__main__":
    main()
